ALTER TABLE users DROP is_deleted;
ALTER TABLE users ADD IF NOT EXISTS is_deleted BOOLEAN;
ALTER TABLE users ADD IF NOT EXISTS gender VARCHAR;
ALTER TABLE users DROP is_deleted;
ALTER TABLE users ADD IF NOT EXISTS is_deleted BOOLEAN;
